server:
  Port: 5005
  Runmode: debug
logger:
  filepath: ../logs/logs.log
  Encoding: json
  level: debug
cors:
  allowOrigins: "*"
postgres:
  host: postgres_container
  port: 5432
  user: postgres
  password: admin
  dbname: car_sale_db
  sslMode: false
redis:
  host: redis_container
  port: 6379
  password: password
  db: 0
  poolSize: 5000
  poolTimeout: 240
  minIdleConnection: 100
